#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.
# +------------------------------------------------------------------+
# | The initial version of this file has been contributed by:        |
# |                                                                  |
# | JR Morgan <liveaverage@gmail.com>                                |
# +------------------------------------------------------------------+

#snmpwalk -v2c 192.168.1.120 -c public .1.3.6.1.4.1.5528.100.4.1.1
#NETBOTZ410-MIB::tempSensorId.3031356659 = STRING: nbAlinkEnc_0_5_TEMP
#NETBOTZ410-MIB::tempSensorId.3056253200 = STRING: nbAlinkEnc_0_6_TEMP
#NETBOTZ410-MIB::tempSensorValue.3031356659 = INTEGER: 171
#NETBOTZ410-MIB::tempSensorValue.3056253200 = INTEGER: 190
#NETBOTZ410-MIB::tempSensorErrorStatus.3031356659 = INTEGER: normal(0)
#NETBOTZ410-MIB::tempSensorErrorStatus.3056253200 = INTEGER: normal(0)
#NETBOTZ410-MIB::tempSensorLabel.3031356659 = STRING: COS-Temp-MDF155
#NETBOTZ410-MIB::tempSensorLabel.3056253200 = STRING: COS-Temp-Q25
#NETBOTZ410-MIB::tempSensorEncId.3031356659 = STRING: nbAlinkEnc_0
#NETBOTZ410-MIB::tempSensorEncId.3056253200 = STRING: nbAlinkEnc_0
#NETBOTZ410-MIB::tempSensorPortId.3031356659 = STRING:
#NETBOTZ410-MIB::tempSensorPortId.3056253200 = STRING:
#NETBOTZ410-MIB::tempSensorValueStr.3031356659 = STRING: 17.100000
#NETBOTZ410-MIB::tempSensorValueStr.3056253200 = STRING: 19.000000
#NETBOTZ410-MIB::tempSensorValueInt.3031356659 = INTEGER: 17
#NETBOTZ410-MIB::tempSensorValueInt.3056253200 = INTEGER: 19
#NETBOTZ410-MIB::tempSensorValueIntF.3031356659 = INTEGER: 62
#NETBOTZ410-MIB::tempSensorValueIntF.3056253200 = INTEGER: 66
#NETBOTZ410-MIB::tempSensorIndex.3031356659 = Counter32: 3031356659
#NETBOTZ410-MIB::tempSensorIndex.3056253200 = Counter32: 3056253200

apc_temp_default_levels = (25, 30)

def inventory_apc_temp(info):
    return [(line[0], "apc_temp_default_levels") for line in info]

def check_apc_temp(item, params, info):
    for name, temp in info:
        if name == item:
            return check_temperature(int(temp), params)

    return (3, "Sensor not found in SNMP data")


check_info["apc_netbotz_temp"] = {
    'check_function':          check_apc_temp,
    'inventory_function':      inventory_apc_temp,
    'service_description':     'Temperature %s',
    'has_perfdata':            True,
    'snmp_info':               ('.1.3.6.1.4.1.5528.100.4.1.1.1', ['4', '8']),
    'snmp_scan_function':      lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.5528.100.20.10."),
    'group':                   'room_temperature',
    'includes':                [ 'temperature.include' ],
}
