#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.
# +------------------------------------------------------------------+
# | The initial version of this file has been contributed by:        |
# |                                                                  |
# | JR Morgan <liveaverage@gmail.com>                                |
# +------------------------------------------------------------------+

#snmpwalk -v2c 192.168.1.120 -c public .1.3.6.1.4.1.5528.100.4.1.2
#NETBOTZ410-MIB::humiSensorId.1121716336 = STRING: nbAlinkEnc_0_6_HUMI
#NETBOTZ410-MIB::humiSensorValue.1121716336 = INTEGER: 270
#NETBOTZ410-MIB::humiSensorErrorStatus.1121716336 = INTEGER: normal(0)
#NETBOTZ410-MIB::humiSensorLabel.1121716336 = STRING: COS-Humidity-Q25
#NETBOTZ410-MIB::humiSensorEncId.1121716336 = STRING: nbAlinkEnc_0
#NETBOTZ410-MIB::humiSensorPortId.1121716336 = STRING:
#NETBOTZ410-MIB::humiSensorValueStr.1121716336 = STRING: 27.000000
#NETBOTZ410-MIB::humiSensorValueInt.1121716336 = INTEGER: 27
#NETBOTZ410-MIB::humiSensorIndex.1121716336 = Counter32: 1121716336


apc_humidity_default_levels = (35, 40, 60, 65)


def inventory_apc_humidity(info):
    return [(line[0], "apc_humidity_default_levels") for line in info]

def check_apc_humidity(item, params, info):
    for line in info:
        if line[0] == item:
            humidity = saveint(line[1])
            critlow, warnlow, warnhigh, crithigh = params
            infotext = "%s%% (warn/crit below %.1f/%.1f or above %.1f/%.1f %%)" % \
                            ( humidity, warnlow, critlow, warnhigh, crithigh)
            perfdata = [ ( "humidity", humidity, critlow, warnlow, warnhigh, crithigh ) ]
            if humidity <= critlow or humidity >= crithigh:
                return (2, "Humidity is: " + infotext, perfdata )
            elif humidity <= warnlow or humidity >= warnhigh:
                return (1, "Humidity is: " + infotext, perfdata )
            else:
                return (0, "Humidity is: " + infotext, perfdata )

    return (3, "sensor not found in SNMP data")


check_info["apc_netbotz_humidity"] = {
    'check_function':          check_apc_humidity,
    'inventory_function':      inventory_apc_humidity,
    'service_description':     'Humidity %s',
    'has_perfdata':            True,
    'snmp_info':               ('.1.3.6.1.4.1.5528.100.4.1.2.1', ['4', '8']),
    'snmp_scan_function':      lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.5528.100.20.10."),
    'group':                   'humidity',
}
